import { useTranslation } from 'react-i18next'
import LanguageSwitcher from './components/LanguageSwitcher'
import Dashboard from './components/Dashboard'
import './App.css'

export default function App() {
  const { t } = useTranslation()

  return (
    <div className="app">
      <header className="header">
        <h1>{t('app.title')}</h1>
        <p>{t('app.tagline')}</p>
        <LanguageSwitcher />
      </header>

      <main>
        <Dashboard />

        <nav className="nav" aria-label={t('nav.overview')}>
          <span>{t('nav.overview')}</span>
          <span>{t('nav.projects')}</span>
          <span>{t('nav.settings')}</span>
        </nav>

        <footer className="footer">
          <p>
            Locale files are generated by <code>npm run i18n</code> before the build.
            This app ships no API key — see the README.
          </p>
          <a href="https://github.com/Shipi18n/shipi18n" target="_blank" rel="noopener noreferrer">
            github.com/Shipi18n/shipi18n
          </a>
        </footer>
      </main>
    </div>
  )
}
